
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 8;
  public static final int FROM = 7;
  public static final int IDENT = 29;
  public static final int SELECT = 6;
  public static final int RPAREN = 23;
  public static final int DATETIME = 19;
  public static final int SEMI = 25;
  public static final int CONTEO = 21;
  public static final int DECIMAL = 20;
  public static final int STAR = 27;
  public static final int ON = 15;
  public static final int AS = 16;
  public static final int LPAREN = 22;
  public static final int TABLE = 5;
  public static final int STRING_LITERAL = 31;
  public static final int VARCHAR = 18;
  public static final int CREATE = 2;
  public static final int COMMA = 24;
  public static final int INSERT = 11;
  public static final int NUMBER = 30;
  public static final int EOF = 0;
  public static final int VALUES = 13;
  public static final int SET = 10;
  public static final int DATABASE = 3;
  public static final int DOT = 26;
  public static final int error = 1;
  public static final int INT_TYPE = 17;
  public static final int ASSIGN = 28;
  public static final int USE = 4;
  public static final int UPDATE = 9;
  public static final int JOIN = 14;
  public static final int INTO = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CREATE",
  "DATABASE",
  "USE",
  "TABLE",
  "SELECT",
  "FROM",
  "WHERE",
  "UPDATE",
  "SET",
  "INSERT",
  "INTO",
  "VALUES",
  "JOIN",
  "ON",
  "AS",
  "INT_TYPE",
  "VARCHAR",
  "DATETIME",
  "DECIMAL",
  "CONTEO",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "SEMI",
  "DOT",
  "STAR",
  "ASSIGN",
  "IDENT",
  "NUMBER",
  "STRING_LITERAL"
  };
}

